version: '3.8'

services:
  automation-dashboard:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./scripts:/app/scripts
    environment:
      - NODE_ENV=production
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
    restart: unless-stopped
